# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealEyesColorado' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealEyesColorado
  pod "youtube-ios-player-helper", "~> 1.0.3"

  target 'RealEyesColoradoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealEyesColoradoUITests' do
    # Pods for testing
  end

end
